# docker-compose.yml
version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./generate_ssl_cert.sh:/usr/local/bin/generate_ssl_cert.sh

volumes:
  wordpress_data:
